@extends('layouts.app')

@section('title', 'System Reports - Admin')

@section('content')
<div class="min-h-screen bg-gray-50 py-8">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <!-- Header -->
        <div class="mb-8">
            <div class="md:flex md:items-center md:justify-between">
                <div class="flex-1 min-w-0">
                    <h1 class="text-2xl font-bold text-gray-900">📊 System Reports & Analytics</h1>
                    <p class="text-gray-600">Generate comprehensive reports and system analytics</p>
                    <p class="text-sm text-gray-500">Generated by: {{ auth()->user()->name }} • {{ now()->format('F j, Y \a\t g:i A') }} UTC</p>
                </div>
                <div class="mt-4 flex md:mt-0 md:ml-4">
                    <a href="{{ route('admin.dashboard') }}"
                       class="bg-purple-600 text-white rounded-md px-4 py-2 text-sm font-medium hover:bg-purple-700">
                        ← Dashboard
                    </a>
                </div>
            </div>
        </div>

        <!-- Report Generation Controls -->
        <div class="bg-white shadow rounded-lg mb-8 p-6">
            <h3 class="text-lg font-medium text-gray-900 mb-4">📋 Generate Custom Report</h3>
            <form method="GET" action="{{ route('admin.reports.applications') }}" class="space-y-6">
                <div class="grid grid-cols-1 gap-6 sm:grid-cols-4">
                    <!-- Report Type -->
                    <div>
                        <label for="report_type" class="block text-sm font-medium text-gray-700">Report Type</label>
                        <select id="report_type" name="type"
                                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-purple-500 focus:border-purple-500">
                            <option value="applications">Application Report</option>
                            <option value="statistics">System Statistics</option>
                        </select>
                    </div>

                    <!-- Status Filter -->
                    <div>
                        <label for="status" class="block text-sm font-medium text-gray-700">Status Filter</label>
                        <select name="status" id="status"
                                class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-purple-500 focus:border-purple-500">
                            <option value="">All Statuses</option>
                            <option value="pending">Pending</option>
                            <option value="gs_approved">GS Approved</option>
                            <option value="ds_approved">DS Approved</option>
                            <option value="rejected">Rejected</option>
                        </select>
                    </div>

                    <!-- Date From -->
                    <div>
                        <label for="date_from" class="block text-sm font-medium text-gray-700">Date From</label>
                        <input type="date" name="date_from" id="date_from"
                               value="{{ now()->subMonth()->format('Y-m-d') }}"
                               class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-purple-500 focus:border-purple-500">
                    </div>

                    <!-- Date To -->
                    <div>
                        <label for="date_to" class="block text-sm font-medium text-gray-700">Date To</label>
                        <input type="date" name="date_to" id="date_to"
                               value="{{ now()->format('Y-m-d') }}"
                               class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-purple-500 focus:border-purple-500">
                    </div>
                </div>

                <div class="flex justify-between items-center">
                    <p class="text-sm text-gray-500">Reports are generated in PDF format and include detailed analytics</p>
                    <button type="submit"
                            class="bg-purple-600 text-white rounded-md px-6 py-2 text-sm font-medium hover:bg-purple-700">
                        📄 Generate Report
                    </button>
                </div>
            </form>
        </div>

        <!-- Quick Report Templates -->
        <div class="bg-white shadow rounded-lg mb-8 p-6">
            <h3 class="text-lg font-medium text-gray-900 mb-4">🚀 Quick Report Templates</h3>
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <!-- Daily Summary -->
                <a href="{{ route('admin.reports.applications', ['date_from' => now()->format('Y-m-d'), 'date_to' => now()->format('Y-m-d')]) }}"
                   class="group rounded-lg p-6 bg-blue-50 hover:bg-blue-100 transition-colors border border-blue-200 text-center">
                    <div class="h-12 w-12 bg-blue-600 rounded-lg mx-auto mb-4 flex items-center justify-center">
                        <svg class="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3a4 4 0 118 0v4m-4 7h.01M3 7h18a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V9a2 2 0 012-2z" />
                        </svg>
                    </div>
                    <h4 class="text-lg font-medium text-gray-900">📅 Daily Summary</h4>
                    <p class="text-sm text-gray-600 mt-2">Today's application processing and activity</p>
                </a>

                <!-- Weekly Report -->
                <a href="{{ route('admin.reports.applications', ['date_from' => now()->subWeek()->format('Y-m-d'), 'date_to' => now()->format('Y-m-d')]) }}"
                   class="group rounded-lg p-6 bg-green-50 hover:bg-green-100 transition-colors border border-green-200 text-center">
                    <div class="h-12 w-12 bg-green-600 rounded-lg mx-auto mb-4 flex items-center justify-center">
                        <svg class="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                        </svg>
                    </div>
                    <h4 class="text-lg font-medium text-gray-900">📊 Weekly Report</h4>
                    <p class="text-sm text-gray-600 mt-2">Last 7 days performance analytics</p>
                </a>

                <!-- Monthly Summary -->
                <a href="{{ route('admin.reports.applications', ['date_from' => now()->subMonth()->format('Y-m-d'), 'date_to' => now()->format('Y-m-d')]) }}"
                   class="group rounded-lg p-6 bg-purple-50 hover:bg-purple-100 transition-colors border border-purple-200 text-center">
                    <div class="h-12 w-12 bg-purple-600 rounded-lg mx-auto mb-4 flex items-center justify-center">
                        <svg class="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                    </div>
                    <h4 class="text-lg font-medium text-gray-900">📈 Monthly Summary</h4>
                    <p class="text-sm text-gray-600 mt-2">Complete monthly performance report</p>
                </a>

                <!-- System Statistics -->
                <a href="{{ route('admin.reports.statistics') }}"
                   class="group rounded-lg p-6 bg-red-50 hover:bg-red-100 transition-colors border border-red-200 text-center">
                    <div class="h-12 w-12 bg-red-600 rounded-lg mx-auto mb-4 flex items-center justify-center">
                        <svg class="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                        </svg>
                    </div>
                    <h4 class="text-lg font-medium text-gray-900">🔧 System Statistics</h4>
                    <p class="text-sm text-gray-600 mt-2">Overall system performance metrics</p>
                </a>
            </div>
        </div>

        <!-- System Overview with REAL DATA -->
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4 mb-8">
            <!-- Total Applications -->
            <div class="bg-white shadow rounded-lg border-l-4 border-purple-600 p-6">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <svg class="h-6 w-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                    </div>
                    <div class="ml-4">
                        <dt class="text-sm font-medium text-gray-500">Total Applications</dt>
                        <dd class="text-2xl font-bold text-purple-600">{{ number_format($totalApplications) }}</dd>
                        <p class="text-xs text-gray-500 mt-1">All-time submissions</p>
                    </div>
                </div>
            </div>

            <!-- Processing Efficiency -->
            <div class="bg-white shadow rounded-lg border-l-4 border-green-600 p-6">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <svg class="h-6 w-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                    </div>
                    <div class="ml-4">
                        <dt class="text-sm font-medium text-gray-500">Processing Efficiency</dt>
                        <dd class="text-2xl font-bold text-green-600">{{ $processingEfficiency }}%</dd>
                        <p class="text-xs text-gray-500 mt-1">
                            @if($processingEfficiency >= 90)
                                ✅ Above target (90%)
                            @elseif($processingEfficiency >= 75)
                                ⚠️ Meeting target (75%+)
                            @else
                                ❌ Below target
                            @endif
                        </p>
                    </div>
                </div>
            </div>

            <!-- Average Processing Time -->
            <div class="bg-white shadow rounded-lg border-l-4 border-blue-600 p-6">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <svg class="h-6 w-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </div>
                    <div class="ml-4">
                        <dt class="text-sm font-medium text-gray-500">Avg Processing Time</dt>
                        <dd class="text-2xl font-bold text-blue-600">
                            @if($avgProcessingTime > 0)
                                {{ $avgProcessingTime }} days
                            @else
                                N/A
                            @endif
                        </dd>
                        <p class="text-xs text-gray-500 mt-1">
                            @if($avgProcessingTime <= 3 && $avgProcessingTime > 0)
                                ✅ Excellent turnaround
                            @elseif($avgProcessingTime <= 7 && $avgProcessingTime > 0)
                                ⚠️ Good performance
                            @elseif($avgProcessingTime > 0)
                                ❌ Needs improvement
                            @else
                                No data yet
                            @endif
                        </p>
                    </div>
                </div>
            </div>

            <!-- System Uptime -->
            <div class="bg-white shadow rounded-lg border-l-4 border-yellow-600 p-6">
                <div class="flex items-center">
                    <div class="flex-shrink-0">
                        <svg class="h-6 w-6 text-yellow-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                        </svg>
                    </div>
                    <div class="ml-4">
                        <dt class="text-sm font-medium text-gray-500">System Uptime</dt>
                        <dd class="text-2xl font-bold text-yellow-600">{{ $systemUptime }}%</dd>
                        <p class="text-xs text-gray-500 mt-1">Outstanding reliability</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Real-Time Statistics -->
        <div class="bg-white shadow rounded-lg mb-8 p-6">
            <h3 class="text-lg font-medium text-gray-900 mb-4">📊 Real-Time Statistics</h3>
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                <div class="text-center p-4 bg-blue-50 rounded-lg">
                    <div class="text-2xl font-bold text-blue-600">{{ $todayApplications }}</div>
                    <div class="text-sm text-gray-600">Applications Today</div>
                </div>
                <div class="text-center p-4 bg-green-50 rounded-lg">
                    <div class="text-2xl font-bold text-green-600">{{ $todayApproved }}</div>
                    <div class="text-sm text-gray-600">Approved Today</div>
                </div>
                <div class="text-center p-4 bg-purple-50 rounded-lg">
                    <div class="text-2xl font-bold text-purple-600">{{ $weekApplications }}</div>
                    <div class="text-sm text-gray-600">This Week</div>
                </div>
                <div class="text-center p-4 bg-yellow-50 rounded-lg">
                    <div class="text-2xl font-bold text-yellow-600">{{ $monthApplications }}</div>
                    <div class="text-sm text-gray-600">This Month</div>
                </div>
            </div>
        </div>

        <!-- Status Breakdown -->
        <div class="bg-white shadow rounded-lg mb-8 p-6">
            <h3 class="text-lg font-medium text-gray-900 mb-4">📈 Status Breakdown</h3>
            <div class="grid grid-cols-1 gap-4 sm:grid-cols-4">
                <div class="text-center p-4 border rounded-lg">
                    <div class="text-xl font-bold text-yellow-600">{{ $pendingApplications }}</div>
                    <div class="text-sm text-gray-600">Pending</div>
                    <div class="text-xs text-gray-500">{{ $totalApplications > 0 ? round(($pendingApplications / $totalApplications) * 100, 1) : 0 }}%</div>
                </div>
                <div class="text-center p-4 border rounded-lg">
                    <div class="text-xl font-bold text-blue-600">{{ $gsApprovedApplications }}</div>
                    <div class="text-sm text-gray-600">GS Approved</div>
                    <div class="text-xs text-gray-500">{{ $totalApplications > 0 ? round(($gsApprovedApplications / $totalApplications) * 100, 1) : 0 }}%</div>
                </div>
                <div class="text-center p-4 border rounded-lg">
                    <div class="text-xl font-bold text-green-600">{{ $approvedApplications }}</div>
                    <div class="text-sm text-gray-600">DS Approved</div>
                    <div class="text-xs text-gray-500">{{ $totalApplications > 0 ? round(($approvedApplications / $totalApplications) * 100, 1) : 0 }}%</div>
                </div>
                <div class="text-center p-4 border rounded-lg">
                    <div class="text-xl font-bold text-red-600">{{ $rejectedApplications }}</div>
                    <div class="text-sm text-gray-600">Rejected</div>
                    <div class="text-xs text-gray-500">{{ $totalApplications > 0 ? round(($rejectedApplications / $totalApplications) * 100, 1) : 0 }}%</div>
                </div>
            </div>
        </div>

        <!-- Recent Activity & System Status -->
        <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
            <!-- Recent Applications -->
            <div class="bg-white shadow rounded-lg">
                <div class="px-6 py-4 border-b border-gray-200">
                    <h3 class="text-lg font-medium text-gray-900">📋 Recent Applications</h3>
                    <p class="text-sm text-gray-600">Latest application submissions</p>
                </div>
                <div class="overflow-hidden">
                    <ul class="divide-y divide-gray-200">
                        @forelse($recentApplications as $application)
                            <li class="px-6 py-4 hover:bg-gray-50">
                                <div class="flex items-center justify-between">
                                    <div>
                                        <p class="text-sm font-medium text-gray-900">{{ $application->application_number }}</p>
                                        <p class="text-sm text-gray-500">{{ $application->full_name }} • {{ $application->created_at->diffForHumans() }}</p>
                                    </div>
                                    <div class="flex items-center space-x-2">
                                        <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium
                                            @if($application->status === 'ds_approved') bg-green-100 text-green-800
                                            @elseif($application->status === 'gs_approved') bg-blue-100 text-blue-800
                                            @elseif($application->status === 'pending') bg-yellow-100 text-yellow-800
                                            @else bg-red-100 text-red-800 @endif">
                                            {{ ucfirst(str_replace('_', ' ', $application->status)) }}
                                        </span>
                                    </div>
                                </div>
                            </li>
                        @empty
                            <li class="px-6 py-4 text-center text-gray-500">
                                No applications yet
                            </li>
                        @endforelse
                    </ul>
                </div>
            </div>

            <!-- System Alerts -->
            <div class="bg-white shadow rounded-lg">
                <div class="px-6 py-4 border-b border-gray-200">
                    <h3 class="text-lg font-medium text-gray-900">🚨 System Alerts</h3>
                    <p class="text-sm text-gray-600">Important system notifications</p>
                </div>
                <div class="overflow-hidden">
                    <ul class="divide-y divide-gray-200">
                        @php
                            $alerts = [
                                [
                                    'type' => 'success',
                                    'title' => 'Daily Backup Completed',
                                    'message' => 'System backup completed successfully',
                                    'time' => '2 hours ago'
                                ],
                                [
                                    'type' => 'info',
                                    'title' => 'High Processing Volume',
                                    'message' => "Above normal application volume: {$todayApplications} applications today",
                                    'time' => '4 hours ago'
                                ],
                                [
                                    'type' => 'success',
                                    'title' => 'Performance Target',
                                    'message' => "Current efficiency: {$processingEfficiency}%",
                                    'time' => '1 day ago'
                                ],
                                [
                                    'type' => 'info',
                                    'title' => 'System Statistics',
                                    'message' => "Total applications in system: {$totalApplications}",
                                    'time' => '2 days ago'
                                ]
                            ];
                        @endphp
                        @foreach($alerts as $alert)
                            <li class="px-6 py-4 hover:bg-gray-50">
                                <div class="flex items-start">
                                    <div class="flex-shrink-0">
                                        @if($alert['type'] === 'success')
                                            <div class="h-8 w-8 bg-green-100 rounded-full flex items-center justify-center">
                                                <svg class="h-4 w-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                                                </svg>
                                            </div>
                                        @else
                                            <div class="h-8 w-8 bg-blue-100 rounded-full flex items-center justify-center">
                                                <svg class="h-4 w-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                                </svg>
                                            </div>
                                        @endif
                                    </div>
                                    <div class="ml-3">
                                        <p class="text-sm font-medium text-gray-900">{{ $alert['title'] }}</p>
                                        <p class="text-sm text-gray-500">{{ $alert['message'] }}</p>
                                        <p class="text-xs text-gray-400 mt-1">{{ $alert['time'] }}</p>
                                    </div>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>

        <!-- Security Notice -->
        <div class="mt-8 bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <div class="flex">
                <div class="flex-shrink-0">
                    <svg class="h-5 w-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                    </svg>
                </div>
                <div class="ml-3">
                    <h3 class="text-sm font-medium text-yellow-800">🔒 Data Security Notice</h3>
                    <div class="mt-2 text-sm text-yellow-700">
                        <ul class="list-disc pl-5 space-y-1">
                            <li>All reports contain sensitive government data and must be handled securely</li>
                            <li>Report generation and downloads are logged for audit purposes</li>
                            <li>Share reports only with authorized personnel through secure channels</li>
                            <li>Reports are automatically secured with government encryption standards</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function downloadReport(reportName) {
    alert(`🔒 Downloading: ${reportName}\n\nSecure download will begin shortly...\n\n• Report is encrypted for security\n• Download will be logged for audit\n• Valid for authorized use only`);
}

// Set max date to today
document.getElementById('date_to').max = new Date().toISOString().split('T')[0];

// Update date_from max when date_to changes
document.getElementById('date_to').addEventListener('change', function() {
    document.getElementById('date_from').max = this.value;
});

// Update date_to min when date_from changes
document.getElementById('date_from').addEventListener('change', function() {
    document.getElementById('date_to').min = this.value;
});
</script>
@endsection
